version: 2

jobs:
  helmLint:
    docker:
      - image: web3f/ci-commons:v3.1.6
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/polkadot-watcher-csv-exporter

  yarnLint:
    docker:
      - image: web3f/node-dind:v1.0.0
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
 

  buildImage:
    docker:
      - image: web3f/ci-commons:v3.1.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run:
          command: |
            /scripts/build-image.sh web3f/polkadot-watcher-csv-exporter .

  publishImage:
    docker:
      - image: web3f/ci-commons:v3.1.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          command: |
            /scripts/publish-image.sh web3f/polkadot-watcher-csv-exporter

  publishChart:
    docker:
      - image: web3f/ci-commons:v3.1.6
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

  integrationTests:
    docker:
      - image: web3f/ci-commons:v3.1.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh kindest/node:v1.21.1           

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - helmLint:
          filters:
            tags:
              only: /.*/
      - yarnLint:
          filters:
            tags:
              only: /.*/        
      - buildImage:
          context: dockerhub-bot
          filters:
            tags:
              only: /.*/
          requires:
            - helmLint
            - yarnLint
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - buildImage       
      - publishImage:
          context: dockerhub-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - integrationTests
      - publishChart:
          context: github-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - integrationTests  
