{{ if eq .Values.loadBalancer.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.loadBalancer.domain }} 
spec:
  type: LoadBalancer
  ports:
  - name: port
    targetPort: 5432
    port: 5432
  selector:
    app.kubernetes.io/instance: postgresql-14
    app.kubernetes.io/name: postgresql
  loadBalancerSourceRanges:
  {{ .Values.loadBalancer.loadBalancerSourceRanges }}   
{{ end }}
