environment: production

image:
  repo: web3f/polkadot-era-scanner-tableau
 # tag: latest

loadBalancer:
  enabled: false
  # domain: yourDomain.com
  # loadBalancerSourceRanges:
  # - 1.2.3.4/32

config:
  logLevel: debug
  healthCheckPort: 8000
  endpoint: 'wss://kusama-rpc.polkadot.io'
  databaseUrl: 'postgres://postgres:postgres@db/postgres'
