environments:
  ci:
  local:

repositories:
  - name: w3f
    url: https://w3f.github.io/helm-charts/

releases:
  - name: polkadot-era-scanner
    chart: ../charts/polkadot-era-scanner
    version: v0.12
    namespace: angela-era-scanner
    values:
      - ./config/polkadot-era-scanner.yaml.gotmpl
