environments:
  ci:
  local:

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgresql-14
    chart: bitnami/postgresql
    version: 11.1.13
    namespace: angela-era-scanner
    values:
      - ./config/postgresql.yaml.gotmpl
